let default = {
  "cite": "Cite.make",
  "info": "Info.make",
  "warn": "Warn.make",
  "image": "Image.make",
  "video": "Video.make",
  "p": "P.make",
  "li": "Li.make",
  "h1": "H1.make",
  "h2": "H2.make",
  "h3": "H3.make",
  "h4": "H4.make",
  "h5": "H5.make",
  "ul": "Ul.make",
  "ol": "Ol.make",
  "hr": "Hr.make",
  "strong": "Strong.make",
  "a": "A.make",
  "pre": "Pre.make",
  "blockquote": "Blockquote.make",
  "code": "Code.make",
}
